/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(cl);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 6:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      if (jj_2_1(2147483647)) {
        ClassDeclaration(cl);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:{
          ThreadDeclaration(cl);
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(37);
    jj_consume_token(7);
    jj_consume_token(9);
    jj_consume_token(21);
    jj_consume_token(8);
    jj_consume_token(35);
    jj_consume_token(22);
    jj_consume_token(39);
    jj_consume_token(40);
    arg = jj_consume_token(ID);
    jj_consume_token(36);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(37);
    label_2:
    while (true) {
      if (jj_2_2(2147483647)) {
        ;
      } else {
        break label_2;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 10:
      case 12:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
      case 35:
      case 37:
      case DECIMAL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(38);
    jj_consume_token(38);

}

// ClassDeclaration 	::= 	"class" Identifier ( "extends" Identifier )? "{" ( VarDeclaration )* ( MethodDeclaration )* "}"
  final public Absyn.ClassDecl ClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.MethodDecl md;
 Absyn.VoidDecl   vd;
 Absyn.VarDecl    fd;
 Token name = null, parent = null;
 String parStr = null;
 LinkedList<Absyn.VarDecl> fields     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
    jj_consume_token(6);
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 14:{
      jj_consume_token(14);
      parent = jj_consume_token(ID);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(37);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:
      case 20:
      case 21:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      VarDeclaration();
fields.add(var);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 7:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      MethodDeclaration();
methods.add(md);
    }
    jj_consume_token(38);
cd = new Absyn.ClassDecl(name.toString(), parent != null ? parent.toString() : null, fields, methods);
        cl.add(cd);
        {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// ThreadDeclaration 	::= 	"class" Identifier "extends" "Thread" "{" ( VarDeclaration )* ( MethodDeclaration | RunDeclaration )* "}"
  final public Absyn.ThreadDecl ThreadDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ThreadDecl cd;
 Absyn.MethodDecl md;
 Absyn.VoidDecl   vd;
 Absyn.VarDecl    fd;
 Token name = null;
 String parStr = null;
 LinkedList<Absyn.VarDecl> fields     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(14);
    jj_consume_token(71);
    jj_consume_token(37);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 7:
      case 19:
      case 20:
      case 21:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_6;
      }
      if (jj_2_3(2147483647)) {
        fd = FieldDeclaration();
fields.add(fd);
      } else if (jj_2_4(2)) {
        vd = VoidDeclaration();
methods.add(vd);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 7:{
          md = MethodDeclaration();
methods.add(md);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(38);
cd = new Absyn.ThreadDecl(name.toString(),
    fields, methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 34:{
      jj_consume_token(34);
      init = Expression();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(41);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

// MethodDeclaration 	::= 	"public" ( "synchronized" )? Type Identifier "(" ( Type Identifier ( "," Type Identifier )* )? ")" "{" ( VarDeclaration )* ( Statement )* "return" Expression ";" "}"
  final public Absyn.MethodDecl MethodDeclaration() throws ParseException {Absyn.Type returnType, paramType;
 Token methodName, paramName;
//	Absyn.Formal formal;
 Absyn.VarDecl var;
 Absyn.Stmt stmt;
 Absyn.Expr expr;
 boolean sync = false;
 LinkedList<Absyn.Formal> formals  = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals  = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts      = new LinkedList<Absyn.Stmt>();
    jj_consume_token(7);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 72:{
      jj_consume_token(72);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    returnType = Type();
    methodName = jj_consume_token(ID);
    jj_consume_token(35);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:
    case 20:
    case 21:
    case ID:{
      paramType = Type();
      paramName = jj_consume_token(ID);
formals.add(new Absyn.Formal(paramType, paramName.toString()));
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 42:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_7;
        }
        jj_consume_token(42);
        paramType = Type();
        paramName = jj_consume_token(ID);
formals.add(new Absyn.Formal(paramType, paramName.toString()));
      }
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(36);
    jj_consume_token(37);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:
      case 20:
      case 21:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_8;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 10:
      case 12:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
      case 35:
      case 37:
      case DECIMAL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_9;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(13);
    expr = Expression();
    jj_consume_token(41);
    jj_consume_token(38);
{if ("" != null) return new Absyn.MethodDecl(returnType, methodName.toString(), formals, locals, stmts, expr);}
    throw new Error("Missing return statement in function");
}

// VoidDeclaration 	::= 	"public" "void" Identifier "(" ( Type Identifier ( "," Type Identifier )* )? ")" "{" ( VarDeclaration )* ( Statement )* "}"
  final public Absyn.VoidDecl VoidDeclaration() throws ParseException {Token methodName;
 Absyn.VarDecl var;
 Absyn.Stmt stmt;
 LinkedList<Absyn.VarDecl> locals  = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts      = new LinkedList<Absyn.Stmt>();
    jj_consume_token(7);
    jj_consume_token(21);
    methodName = jj_consume_token(ID);
    jj_consume_token(35);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:
    case 20:
    case 21:
    case ID:{
      Type();
      paramName = jj_consume_token(ID);
formals.add(new Absyn.Formal(type, paramName.toString()));
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 42:{
          ;
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          break label_10;
        }
        jj_consume_token(42);
        Type();
        paramName = jj_consume_token(ID);
formals.add(new Absyn.Formal(type, paramName.toString()));
      }
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(36);
    jj_consume_token(37);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 19:
      case 20:
      case 21:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_11;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 10:
      case 12:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
      case 35:
      case 37:
      case DECIMAL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_12;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(38);
{if ("" != null) return new Absyn.VoidDecl(methodName.toString(), formals, locals, stmts);}
    throw new Error("Missing return statement in function");
}

// FieldDeclaration 	::= 	Type Identifier ";"
  final public Absyn.VarDecl FieldDeclaration() throws ParseException {Absyn.Type type;
 Token name;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 34:{
      jj_consume_token(34);
      init = Expression();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(41);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 37:{
      s = Block();
      break;
      }
    case 10:{
      s = IfStatement();
      break;
      }
    case 12:{
      s = WhileStatement();
      break;
      }
    case 17:
    case 18:
    case 35:
    case DECIMAL:
    case ID:{
      s = ExpressionStatement();
      break;
      }
    case 19:
    case 20:
    case 21:{
      s = VarDeclaration();
{if ("" != null) return s;}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Absyn.Stmt IfStatement() throws ParseException {Absyn.Expr cond;
    Absyn.Stmt thenStmt, elseStmt = null;
    jj_consume_token(10);
    jj_consume_token(35);
    cond = Expression();
    jj_consume_token(36);
    thenStmt = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 11:{
      jj_consume_token(11);
      elseStmt = Statement();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.IfStmt(cond, thenStmt, elseStmt);}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Type Type() throws ParseException {Absyn.Type t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:{
      jj_consume_token(19);
t = new Absyn.IntegerType();
      break;
      }
    case 20:{
      jj_consume_token(20);
t = new Absyn.BooleanType();
      break;
      }
    case 21:{
      jj_consume_token(21);
t = new Absyn.VoidType();
      break;
      }
    case ID:{
      jj_consume_token(ID);
t = new Absyn.IdentifierType(token.image);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Absyn.Expr PrimaryExpression() throws ParseException {Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 17:
    case 18:
    case DECIMAL:{
      e = Literal();
      break;
      }
    case ID:{
      e = jj_consume_token(ID);
      break;
      }
    case 35:{
      jj_consume_token(35);
      e = Expression();
      jj_consume_token(36);
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e, right;
    Token op;
    e = PrimaryExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 73:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_13;
      }
      op = BinaryOperator();
      right = PrimaryExpression();
e = new Absyn.BinaryExpr(e, right, op.image);
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Expr Literal() throws ParseException {Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DECIMAL:{
      e = jj_consume_token(DECIMAL);
{if ("" != null) return new Absyn.IntLiteral(Integer.parseInt(token.image));}
      break;
      }
    case 17:{
      jj_consume_token(17);
{if ("" != null) return new Absyn.BooleanLiteral(true);}
      break;
      }
    case 18:{
      jj_consume_token(18);
{if ("" != null) return new Absyn.BooleanLiteral(false);}
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Absyn.Stmt Block() throws ParseException {LinkedList<Absyn.Stmt> stmts = new LinkedList<Absyn.Stmt>();
    jj_consume_token(37);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 10:
      case 12:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
      case 35:
      case 37:
      case DECIMAL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_14;
      }
      Statement();
stmts.add(stmt);
    }
    jj_consume_token(38);
{if ("" != null) return new Absyn.Block(stmts);}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Stmt WhileStatement() throws ParseException {Absyn.Expr cond;
    Absyn.Stmt body;
    jj_consume_token(12);
    jj_consume_token(35);
    cond = Expression();
    jj_consume_token(36);
    body = Statement();
{if ("" != null) return new Absyn.WhileStmt(cond, body);}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Stmt ExpressionStatement() throws ParseException {Absyn.Expr e;
    e = Expression();
    jj_consume_token(41);
{if ("" != null) return new Absyn.ExprStmt(e);}
    throw new Error("Missing return statement in function");
}

  final public Token BinaryOperator() throws ParseException {Token t;
    t = jj_consume_token(73);
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
}

  final public Absyn.Expr BinaryOperation() throws ParseException {Absyn.Expr left, right;
    Token op;
    left = Expression();
    op = BinaryOperator();
    right = Expression();
{if ("" != null) return new Absyn.BinaryExpr(left, right, op.image);}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_3R_IfStatement_371_5_48()
 {
    if (jj_scan_token(10)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    if (jj_scan_token(36)) return true;
    if (jj_3R_Statement_357_5_37()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_IfStatement_373_7_55()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_VarDeclaration_276_2_16()
 {
    if (jj_3R_Type_382_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_276_30_23()) jj_scanpos = xsp;
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3R_BinaryOperator_458_5_40()
 {
    if (jj_scan_token(73)) return true;
    return false;
  }

  private boolean jj_3R_Statement_361_5_45()
 {
    if (jj_3R_VarDeclaration_276_2_16()) return true;
    return false;
  }

  private boolean jj_3R_Statement_360_5_44()
 {
    if (jj_3R_ExpressionStatement_449_5_50()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_FieldDeclaration_344_3_17()) return true;
    return false;
  }

  private boolean jj_3R_Statement_359_5_43()
 {
    if (jj_3R_WhileStatement_439_5_49()) return true;
    return false;
  }

  private boolean jj_3R_Statement_358_5_42()
 {
    if (jj_3R_IfStatement_371_5_48()) return true;
    return false;
  }

  private boolean jj_3R_Statement_357_5_37()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Statement_357_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_358_5_42()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_359_5_43()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_360_5_44()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_361_5_45()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Statement_357_5_41()
 {
    if (jj_3R_Block_427_5_47()) return true;
    return false;
  }

  private boolean jj_3R_ExpressionStatement_449_5_50()
 {
    if (jj_3R_Expression_406_5_30()) return true;
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_VoidDeclaration_323_2_18()) return true;
    return false;
  }

  private boolean jj_3R_FieldDeclaration_345_7_24()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    return false;
  }

  private boolean jj_3R_WhileStatement_439_5_49()
 {
    if (jj_scan_token(12)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    if (jj_scan_token(36)) return true;
    if (jj_3R_Statement_357_5_37()) return true;
    return false;
  }

  private boolean jj_3R_FieldDeclaration_344_3_17()
 {
    if (jj_3R_Type_382_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_FieldDeclaration_345_7_24()) jj_scanpos = xsp;
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3R_Block_428_7_54()
 {
    if (jj_3R_Statement_357_5_37()) return true;
    return false;
  }

  private boolean jj_3R_Block_427_5_47()
 {
    if (jj_scan_token(37)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Block_428_7_54()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(38)) return true;
    return false;
  }

  private boolean jj_3R_ClassDeclaration_232_7_21()
 {
    if (jj_3R_MethodDeclaration_296_2_25()) return true;
    return false;
  }

  private boolean jj_3R_ClassDeclaration_231_7_20()
 {
    if (jj_3R_VarDeclaration_276_2_16()) return true;
    return false;
  }

  private boolean jj_3R_ClassDeclaration_229_7_19()
 {
    if (jj_scan_token(14)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_Literal_419_5_53()
 {
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_Literal_418_5_52()
 {
    if (jj_scan_token(17)) return true;
    return false;
  }

  private boolean jj_3R_Literal_417_5_51()
 {
    if (jj_scan_token(DECIMAL)) return true;
    return false;
  }

  private boolean jj_3R_Literal_417_5_46()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Literal_417_5_51()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_418_5_52()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_419_5_53()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_ClassDeclaration_228_2_15()
 {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ClassDeclaration_229_7_19()) jj_scanpos = xsp;
    if (jj_scan_token(37)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ClassDeclaration_231_7_20()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ClassDeclaration_232_7_21()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(38)) return true;
    return false;
  }

  private boolean jj_3R_VoidDeclaration_323_2_18()
 {
    if (jj_scan_token(7)) return true;
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3R_Expression_407_7_35()
 {
    if (jj_3R_BinaryOperator_458_5_40()) return true;
    if (jj_3R_PrimaryExpression_394_5_34()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_VarDeclaration_276_2_16()) return true;
    return false;
  }

  private boolean jj_3R_Expression_406_5_30()
 {
    if (jj_3R_PrimaryExpression_394_5_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Expression_407_7_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_MethodDeclaration_304_7_33()
 {
    if (jj_3R_Statement_357_5_37()) return true;
    return false;
  }

  private boolean jj_3R_MethodDeclaration_303_7_32()
 {
    if (jj_3R_VarDeclaration_276_2_16()) return true;
    return false;
  }

  private boolean jj_3R_MethodDeclaration_300_9_36()
 {
    if (jj_scan_token(42)) return true;
    if (jj_3R_Type_382_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_VarDeclaration_276_30_23()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    return false;
  }

  private boolean jj_3R_MethodDeclaration_299_7_31()
 {
    if (jj_3R_Type_382_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_300_9_36()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_PrimaryExpression_396_5_39()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3R_PrimaryExpression_394_5_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_394_5_38()) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_396_5_39()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_PrimaryExpression_394_5_38()
 {
    if (jj_3R_Literal_417_5_46()) return true;
    return false;
  }

  private boolean jj_3R_MethodDeclaration_296_2_25()
 {
    if (jj_scan_token(7)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) jj_scanpos = xsp;
    if (jj_3R_Type_382_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(35)) return true;
    xsp = jj_scanpos;
    if (jj_3R_MethodDeclaration_299_7_31()) jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    if (jj_scan_token(37)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_303_7_32()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MethodDeclaration_304_7_33()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(13)) return true;
    if (jj_3R_Expression_406_5_30()) return true;
    if (jj_scan_token(41)) return true;
    if (jj_scan_token(38)) return true;
    return false;
  }

  private boolean jj_3R_Type_385_5_29()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_Type_384_5_28()
 {
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3R_Type_383_5_27()
 {
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3R_Type_382_5_26()
 {
    if (jj_scan_token(19)) return true;
    return false;
  }

  private boolean jj_3R_Type_382_5_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Type_382_5_26()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_383_5_27()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_384_5_28()) {
    jj_scanpos = xsp;
    if (jj_3R_Type_385_5_29()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_ClassDeclaration_228_2_15()) return true;
    return false;
  }

  private boolean jj_3R_IfStatement_373_7_55()
 {
    if (jj_scan_token(11)) return true;
    if (jj_3R_Statement_357_5_37()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MiniJavaParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x40,0x40,0x3e1400,0x4000,0x380000,0x80,0x380080,0x80,0x0,0x0,0x0,0x380000,0x380000,0x3e1400,0x0,0x380000,0x380000,0x3e1400,0x0,0x3e1400,0x800,0x380000,0x60000,0x0,0x60000,0x3e1400,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x80000028,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x400,0x0,0x0,0x80000028,0x400,0x0,0x0,0x80000028,0x4,0x80000028,0x0,0x0,0x80000008,0x0,0x80000000,0x80000028,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x8,0x0,0x8,0x0,0x8,0x0,0x0,0x100,0x0,0x8,0x8,0x8,0x0,0x8,0x8,0x8,0x0,0x8,0x0,0x8,0x8,0x200,0x0,0x8,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[4];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 26; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[74];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 26; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 74; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 4; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
