/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 59;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 60;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 61;
  /** RegularExpression Id. */
  int DECIMAL = 63;
  /** RegularExpression Id. */
  int OCTAL = 64;
  /** RegularExpression Id. */
  int HEXADECIMAL = 65;
  /** RegularExpression Id. */
  int BINARY = 66;
  /** RegularExpression Id. */
  int ID = 67;
  /** RegularExpression Id. */
  int LETTER = 68;
  /** RegularExpression Id. */
  int DIGIT = 69;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"class\"",
    "\"public\"",
    "\"main\"",
    "\"static\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"extends\"",
    "\"new\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"boolean\"",
    "\"void\"",
    "\"String\"",
    "\"null\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"Xinu.print\"",
    "\"Xinu.println\"",
    "\"Xinu.printint\"",
    "\"Xinu.readint\"",
    "\"Xinu.sleep\"",
    "\"Xinu.signal\"",
    "\"Xinu.wait\"",
    "\"Xinu.semcreate\"",
    "\"Xinu.semsignal\"",
    "\"Xinu.semwait\"",
    "\"Xinu.resume\"",
    "\"Xinu.suspend\"",
    "\"//\"",
    "<token of kind 57>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 62>",
    "<DECIMAL>",
    "<OCTAL>",
    "<HEXADECIMAL>",
    "<BINARY>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 70>",
    "\"Thread\"",
    "\"synchronized\"",
    "<token of kind 73>",
  };

}
