/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 57;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 58;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 59;
  /** RegularExpression Id. */
  int DECIMAL = 61;
  /** RegularExpression Id. */
  int OCT = 62;
  /** RegularExpression Id. */
  int HEXADECIMAL = 63;
  /** RegularExpression Id. */
  int BIN = 64;
  /** RegularExpression Id. */
  int ID = 65;
  /** RegularExpression Id. */
  int LETTER = 66;
  /** RegularExpression Id. */
  int DIGIT = 67;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"class\"",
    "\"else\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"boolean\"",
    "\"int\"",
    "\"new\"",
    "\"main\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"double\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"Xinu.print\"",
    "\"Xinu.println\"",
    "\"Xinu.printint\"",
    "\"Xinu.readint\"",
    "\"Xinu.sleep\"",
    "\"Xinu.signal\"",
    "\"Xinu.wait\"",
    "\"Xinu.semcreate\"",
    "\"Xinu.semsignal\"",
    "\"Xinu.semwait\"",
    "\"Xinu.resume\"",
    "\"Xinu.suspend\"",
    "\"//\"",
    "<token of kind 55>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 60>",
    "<DECIMAL>",
    "<OCT>",
    "<HEXADECIMAL>",
    "<BIN>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 68>",
    "\"extends\"",
    "\"Thread\"",
    "\"synchronized\"",
    "<token of kind 72>",
  };

}
